# Opções de financiamento para este projeto

# GitHub Sponsors (adicione seu username quando aprovado)
# github: aroldobossoni

# Custom donation links
custom:
  - "https://aroldobossoni.github.io/machinist-MD8/#donation"

